[project]
name = "iesopt-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "iesopt>=2.7.0",
    "matplotlib>=3.10.3",
    "plotly>=6.1.2",
]
